Shuttlerock/actions

.meta/STUDIO-610.md
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Github/Epic.ts
src/services/Github/__tests__/Epic.test.ts
src/services/Jira/Issue.ts
src/services/Jira/__tests__/Issue.test.ts
src/tests/fixtures/jira-pull-requests.json
src/triggers/createPullRequestForJiraIssue.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-610)
Trigger PR creation for an issue whose Epic has PRs in multiple repositories (eg. [STUDIO-606](https://shuttlerock.atlassian.net/browse/STUDIO-606)). It shouldn't explode when it hits the wrong repo.
**Note: This is tested and working**
None

[STUDIO-610] Fix missing filtering of pull requests by repository when creating PRs

---

.meta/STUDIO-652.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
src/services/Github/__tests__/Epic.test.ts
src/services/Github/__tests__/Label.test.ts
src/services/Jira/Issue.ts
src/services/Jira/__tests__/Issue.test.ts
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-652)
Eg. [https:&#x2F;&#x2F;shuttlerock.atlassian.net&#x2F;browse&#x2F;STUDIO-643|https:&#x2F;&#x2F;shuttlerock.atlassian.net&#x2F;browse&#x2F;STUDIO-643|smart-link]  - we didn’t need to make a PR here. Maybe we can have some kind of label that will allow it to be skipped? Alternatively we could not-fill-in-the-repository-field
Add the `Skip_PR` label to an epic, and then create a PR for one of its children.  The Epic PR should not be created.
None

[STUDIO-652] Allow a label to be added to Jira issues to skip PR creation

---

.meta/STUDIO-961.md
actions/trigger-action/index.js
src/triggers/createPullRequestForJiraIssue.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-961)
See https://github.com/Shuttlerock/spielberg-ui/runs/1456190355?check_suite_focus=true
Trigger automation to move an unassigned PR to `In Development`, and make sure no error occurs in the action.
None

[STUDIO-961] Fix issue triggering pull request creation when issues are moved by Shuttlebot

---

actions/check-run-completed-action/index.js
actions/trigger-action/index.js
src/services/Slack/Message.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1081)
Eg. https:&#x2F;&#x2F;github.com&#x2F;Shuttlerock&#x2F;spielberg-ui&#x2F;runs&#x2F;1507730511?check_suite_focus&#x3D;true
If tests pass, it should be fine - it just improves error handling.
None.

[STUDIO-1081] Catch errors when sending messages to invalid Slack accounts

---

actions/check-run-completed-action/index.js
src/actions/check-run-completed-action/checkRunCompleted.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1083)
This should stop the stream of repeated `Has Issues` slack messages, but I'm not sure how to trigger it...
None

[STUDIO-1083] Only send the 'Has Issues' Slack message when the issue is moved, to avoid duplicates

---

actions/trigger-action/index.js
src/tests/fixtures/jira-issue.json
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/__tests__/jiraStoryPointsUpdated.test.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1183)
Move a Jira issue *with no point estimate* to `In Development`. You should get a slack message warning you that the PR could not be created.
None

[STUDIO-1183] Block PR creation if no points estimate has been entered for the issue

---

actions/trigger-action/index.js
src/triggers/__tests__/jiraIssueTransitioned.test.ts
src/triggers/jiraIssueTransitioned.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1198)
Make an Epic with one child issue,. and move the child issue to `Validated`. The Epic should not move.
None

[STUDIO-1198] Don't automatically move epics to 'Validated'

---

actions/trigger-action/index.js
src/triggers/jiraIssueTransitioned.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1201)
Move an issue with children that are in the backlog to any status except `Ready for planning`. The children should be moved to the board (if they weren't there already).
None

[STUDIO-1201] If the status of a parent issue changes, move all of the subtasks to the board

---

actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Jira/Issue.ts
src/triggers/__tests__/jiraIssueTransitioned.test.ts
src/triggers/jiraIssueTransitioned.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1206)
Transition a card to `In development`, when there are other cards in the same epic in `Technical Planning`. The epic should be marked as `In development` rather than `Technical Planning`.
None

[STUDIO-1206] If any children of an epic are 'In development', then the epic should also be in 'In development'

---

package.json
yarn.lock

- 5b0c248 Bump @slack/web-api from 5.14.0 to 5.15.0
- 5557e8a Bump @typescript-eslint/parser from 4.11.1 to 4.12.0
- 1882882 Bump eslint-plugin-prettier from 3.3.0 to 3.3.1
- a402e87 Bump @types/node from 14.14.19 to 14.14.20

Release Candidate 2021-01-07-0455 (Quiet Quokka)

---

.meta/STUDIO-1267.md
actions/pull-request-ready-for-review-action/index.js
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1267)
See [https:&#x2F;&#x2F;github.com&#x2F;Shuttlerock&#x2F;pitch-deck&#x2F;pull&#x2F;37&#x2F;checks?check_run_id&#x3D;1667144484|https:&#x2F;&#x2F;github.com&#x2F;Shuttlerock&#x2F;pitch-deck&#x2F;pull&#x2F;37&#x2F;checks?check_run_id&#x3D;1667144484]
{noformat}Getting the Jira key from the pull request pitch-deck#37...
14Couldn&#39;t extract a Jira issue key from pitch-deck#37 - ignoring{noformat}
Since there is no Jira issue attached to a release, the {{please-review}} label never gets added. We shouldn’t give up in this case.
Set a release to `ready for review` - reviewers should be added correctly.
None

[STUDIO-1267] Fix ready-for-review action for release PRs

---

.meta/STUDIO-1283.md
actions/pull-request-ready-for-review-action/index.js
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1283)
Release, then make another release PR and set it to `Ready for review` - the `please-review` label should be added.
None

[STUDIO-1283] Fix adding labels to release PRs when they are made ready for review

---

.meta/STUDIO-1291.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Github/Release.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1291)
Make a release PR, and check that dependabot links don't display the git SHA.
None

[STUDIO-1291] Don't include the Git hash in dependabot summary in release PRs

---

package.json
yarn.lock

- Bump dateformat from 4.4.1 to [4.4.2](https://github.com/Shuttlerock/actions/commit/cfe2dc86ce11e9be1f7b9e9d0f6051308f8a77a5)

Release Candidate 2021-01-22-1247 (Juicy Jay)

---

.meta/STUDIO-1463.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/actions/trigger-action/__tests__/fixtures/approvePullRequest.json
src/actions/trigger-action/index.ts
src/services/Credentials.ts
src/services/Github/PullRequest.ts
src/services/Github/__tests__/PullRequest.test.ts
src/services/Slack/Message.ts
src/tests/Mocks.ts
src/triggers/__tests__/approvePullRequest.test.ts
src/triggers/approvePullRequest.ts
src/triggers/index.ts
yarn.lock

- #344 Allow selected repositories to be auto-approved via Slack ([STUDIO-1463](https://shuttlerock.atlassian.net/browse/STUDIO-1463))
- Bump dateformat from 4.5.0 to [4.5.1](https://github.com/Shuttlerock/actions/commit/f5a9df1bed6c29284cc27b7df143ddb25af7a17c)
- Bump eslint from 7.18.0 to [7.19.0](https://github.com/Shuttlerock/actions/commit/c67752e4393cc5fce5802fddfc36a7c87b8890bb)
- Bump ts-jest from 26.4.4 to [26.5.0](https://github.com/Shuttlerock/actions/commit/c22a9221e439749c35bdba35287a044722a56f9b)
- Bump eslint-plugin-jsdoc from 31.4.0 to [31.6.0](https://github.com/Shuttlerock/actions/commit/9706be0dff309542280f634c66d868101d5d05cb)
- Bump @octokit/webhooks from 7.21.0 to [7.24.2](https://github.com/Shuttlerock/actions/commit/b79bd21051a8fee1fbad531ced5ef199815f01c2)
- Bump …

Release Candidate 2021-02-05-0624 (Universal Urial)

---

.circleci/config.yml
.eslintrc.js
.meta/STUDIO-1567.md
.meta/STUDIO-1568.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/services/Github/Release.ts
src/services/Github/__tests__/Release.test.ts
yarn.lock

- #383 Don't assume that a commit author will have a Github login, take 2 ([STUDIO-1567](https://shuttlerock.atlassian.net/browse/STUDIO-1567))
- #385 Use a bigger CircleCI instance for selected tests ([STUDIO-1568](https://shuttlerock.atlassian.net/browse/STUDIO-1568))
- Bump eslint-plugin-unused-imports from 1.0.3 to [1.1.0](https://github.com/Shuttlerock/actions/commit/6671a04fda170064446f5ff436354c6e0220ac12)
- Bump ts-jest from 26.5.0 to [26.5.2](https://github.com/Shuttlerock/actions/commit/fc22587c398636d8b601a487a7bf1849eb2c0d36)
- Bump unique-names-generator from 4.3.1 to [4.4.0](https://github.com/Shuttlerock/actions/commit/9f0e9426c2d481cfa9944932455b2cf17fe8fafa)
- Bump eslint from 7.19.0 to [7.20.0](https://github.com/Shuttlerock/actions/commit/f4fdb7dcdf6982f844729e7db7f7c912 …

Release Candidate 2021-02-24-0258 (Zealous Zebra)

---

.meta/SHARED-69.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-converted-to-draft-action/__tests__/pullRequestConvertedToDraft.test.ts
src/actions/pull-request-converted-to-draft-action/pullRequestConvertedToDraft.ts
src/services/Jira/Issue.ts
src/services/Jira/Project.ts
src/services/Jira/__tests__/Project.test.ts
src/triggers/__tests__/jiraIssueTransitioned.test.ts
src/triggers/jiraIssueTransitioned.ts

[Jira Chore](https://shuttlerock.atlassian.net/browse/SHARED-69)
Currently we use &#x60;In Progress&#x60; instead of &#x60;In Development&#x60; in the &#x60;Security&#x60; board. We want to make sure we can create PRs there without throwing errors.
Create a PR for `compliance` repo via the SECURITY project in Jira, by moving to the `In progress` column.
None

[SHARED-69] Support Jira state names from the Security project

---

.meta/SECURITY-207.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-ready-for-review-action/__tests__/pullRequestReadyForReview.test.ts
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
src/services/Jira/Issue.ts
src/services/Jira/Project.ts
src/services/Jira/__tests__/Project.test.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Task](https://shuttlerock.atlassian.net/browse/SECURITY-207)
Some boards call it &#x60;Tech review&#x60;, others just &#x60;Review&#x60;.
Mark a security issue as `Ready for review`
None

[SECURITY-207] Handle 'Review' column during Jira automation

---

.meta/SECURITY-207.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/actions/pull-request-ready-for-review-action/__tests__/pullRequestReadyForReview.test.ts
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
src/services/Jira/Issue.ts
src/services/Jira/Project.ts
src/services/Jira/__tests__/Project.test.ts
src/triggers/createPullRequestForJiraIssue.ts
yarn.lock

- #424 Handle 'Review' column during Jira automation ([SECURITY-207](https://shuttlerock.atlassian.net/browse/SECURITY-207))
- Bump eslint-plugin-github from 4.1.1 to [4.1.2](https://github.com/Shuttlerock/actions/commit/c69efff286afc8823fa9c6ac83fd76e76643f096)
- Bump @typescript-eslint/parser from 4.16.1 to [4.17.0](https://github.com/Shuttlerock/actions/commit/7cfe6683f3bd9d2af263c191ecdb6ca63c84b7a6)
- Bump eslint-plugin-jest from 24.1.5 to [24.3.1](https://github.com/Shuttlerock/actions/commit/1648ee752d2f8d3b37d8c3d36e5b3f69f5871685)
- Bump @slack/web-api from 6.0.0 to [6.1.0](https://github.com/Shuttlerock/actions/commit/9a64b49237ceb9b62398c8a9a4ad55aea274f293)
- Bump @types/node from 14.14.32 to [14.14.34](https://github.com/Shuttlerock/actions/commit/b7ca622436b8b3234a61e332e14c3 …

Release Candidate 2021-03-16-0632 (Narrow Narwhal)

---

.meta/SECURITY-177.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/actions/pull-request-ready-for-review-action/__tests__/pullRequestReadyForReview.test.ts
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
src/services/Constants.ts

[Jira Task](https://shuttlerock.atlassian.net/browse/SECURITY-177)
This will address the Vanta _“Records of security issues being assigned to owners”_ control.
Edit `pull-request-labeled.json` so that it adds the `security` label, and then run:
`act --job pull_request_labeled_action --eventpath src/actions/pull-request-labeled-action/__tests__/fixtures/pull-request-labeled.json`
None

[SECURITY-177] Auto-assign dependabot and security PRs to the project tech lead

---

.meta/SECURITY-238.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
src/actions/pull-request-closed-action/pullRequestClosed.ts
src/services/Jira/Project.ts
src/services/Jira/__tests__/Project.test.ts

[Jira Task](https://shuttlerock.atlassian.net/browse/SECURITY-238)
Some Jira projects don&#39;t have this column - we should fail gracefully in this case.
Merge a PR and check that the Jira issue is moved to `Validated`.
None

[SECURITY-238] Handle 'Validated' column during Jira automation

---

.meta/SHARED-75.md
actions/pull-request-labeled-action/index.js
src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
src/actions/pull-request-labeled-action/pullRequestLabeled.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/SHARED-75)
Refactoring introduced in https:&#x2F;&#x2F;github.com&#x2F;Shuttlerock&#x2F;actions&#x2F;pull&#x2F;434 no longer performs mutually-exclusive-label check.
Add the `passed-review` label to a PR - it should remove `please-review`.
None

[SHARED-75] Fix mutually-exclusive label assignment

---

.meta/SECURITY-334.md
actions/trigger-action/index.js
src/triggers/__tests__/jiraIssueTransitioned.test.ts
src/triggers/jiraIssueTransitioned.ts

[Jira Task](https://shuttlerock.atlassian.net/browse/SECURITY-334)
[Jira Epic](https://shuttlerock.atlassian.net/browse/SECURITY-244)
Status names for board columns don&#39;t necessarily have the same case as the same status within the Issue API response. Jira seems to capitalize the name in the issues, leading to an elusive bug where statuses couldn&#39;t be found.
Move an issue belonging to an epic to `In progress` in the `SECURITY` board. The board status is `In progress`, but the issue status becomes `In Progress` with a capital `P`. This PR should handle the mismatch gracefully.
None

[SECURITY-334] Fix case-insensitivity issue in Jira status names

---

.meta/SECURITY-334.md
actions/trigger-action/index.js
package.json
src/triggers/__tests__/jiraIssueTransitioned.test.ts
src/triggers/jiraIssueTransitioned.ts
yarn.lock

- #458 Fix case-insensitivity issue in Jira status names ([SECURITY-334](https://shuttlerock.atlassian.net/browse/SECURITY-334))
- Bump @types/node from 14.14.35 to [14.14.37](https://github.com/Shuttlerock/actions/commit/19bf7d05ba0ff718279ebc12f2f2c4ed464a05f1)
- Bump @octokit/webhooks from 8.8.0 to [8.8.2](https://github.com/Shuttlerock/actions/commit/89168b2bd106b262071e4e73593829aa149adfe6)
- Bump y18n from 4.0.0 to [4.0.1](https://github.com/Shuttlerock/actions/commit/990309c527fd0b01f70f74b0e41ebf8b2ede1e0c)
- Bump eslint from 7.22.0 to [7.23.0](https://github.com/Shuttlerock/actions/commit/d1f3e7fa2379fc345abb9e0399ce8b1f6cd2e9e5)
- Bump @octokit/webhooks from 8.8.2 to [8.8.3](https://github.com/Shuttlerock/actions/commit/13e46fe8a0a87ecd781f64942e73e226db39c660)
- Bump ts-jest …

Release Candidate 2021-04-02-0351 (Selfish Starfish)

---

.meta/STUDIO-1859.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Github/Release.ts

[Jira Chore](https://shuttlerock.atlassian.net/browse/STUDIO-1859)
Currently we get 404s and creation fails, if a PR can&#39;t be found while creating notes.
Create a release and make sure everything works.
None

[STUDIO-1859] Handle errors during release creation more gracefully

---

actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/check-suite-completed-action/__tests__/checkSuiteCompleted.test.ts
src/actions/check-suite-completed-action/checkSuiteCompleted.ts

[Jira Story](https://shuttlerock.atlassian.net/browse/STUDIO-1863)
Don't move the jira status to the has issues column (or anywhere) when the checks fail on a PR.
When a PR's checks fail, leave its Jira task alone.
Deploy notes
-------------
none

[#471][STUDIO-1863] Do not move Jira task when checks fail

---

.meta/SECURITY-381.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Template.ts

[Jira Task](https://shuttlerock.atlassian.net/browse/SECURITY-381)
For some reason the import structure has changed, and we now get &#x60;(0 , mustache_namespaceObject.render) is not a function&#x60;.
Create a PR via automation - if no errors are thrown, it works.
None

[SECURITY-381] Fix mustache template errors during PR automation

---

actions/trigger-action/index.js
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/createPullRequestForJiraIssue.ts

`createPullRequestForJiraIssue` needs to be able to receive the repository from `slack-bot` and use it in place of currently obtaining the repository through Jira issues.

Allow Creation of Jira Issue Pull Request to Receive Repository Param

---

.meta/SECURITY-381.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/services/Template.ts
yarn.lock

- #513 Fix mustache template errors during PR automation ([SECURITY-381](https://shuttlerock.atlassian.net/browse/SECURITY-381))
- Bump eslint from 7.24.0 to [7.25.0](https://github.com/Shuttlerock/actions/commit/72ebde49acc50bdf3152b21404d6ed345961245c)
- Bump @types/jest from 26.0.22 to [26.0.23](https://github.com/Shuttlerock/actions/commit/1d5cc2d6dfca6abfd561257c7457f7f5c9a2a978)
- Bump @types/node from 14.14.41 to [15.0.2](https://github.com/Shuttlerock/actions/commit/fdb9f5865cdbe1de7ee9bcafcbe9596c6ebc4d5b)
- Bump @typescript-eslint/parser from 4.22.0 to [4.22.1](https://github.com/Shuttlerock/actions/commit/3c28aea49f9b590c045203700b7e484623074a02)
- Bump ts-jest from 26.5.5 to [26.5.6](https://github.com/Shuttlerock/actions/commit/4b511dde28bf03b06ca5ce29b907ffdfa75d1a84)
- Bump …

Release Candidate 2021-05-06-0257 (Qualified Quelea)

---

actions/pull-request-closed-action/index.js
src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
src/actions/pull-request-closed-action/pullRequestClosed.ts
src/services/Credentials.ts
src/tests/Mocks.ts

The recent boolean to make adding Jira releases option has flawed logic. This is to update the `action` repo to use the updated logic.
Tests should be green
Deployment Notes
None

Fix for Jira release boolean logic

---

actions/pull-request-closed-action/index.js
package.json
src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
src/actions/pull-request-closed-action/pullRequestClosed.ts
src/services/Credentials.ts
src/tests/Mocks.ts
yarn.lock

- Bump unique-names-generator from 4.4.0 to [4.5.0](https://github.com/Shuttlerock/actions/commit/bb791cfc979a59f849b3b410429f6476833fa8c5)
- Bump eslint-plugin-import from 2.22.1 to [2.23.2](https://github.com/Shuttlerock/actions/commit/5f9795725f27f1b8cbb00b80e7003383f2eb9dff)

Release Candidate 2021-05-21-1244 (Jolly Jaguar)

---

package.json
yarn.lock

- Bump eslint from 7.26.0 to [7.27.0](https://github.com/Shuttlerock/actions/commit/c674371ffc54508a0227dcda1fbb14adcdd81556)
- Bump typescript from 4.2.4 to [4.3.2](https://github.com/Shuttlerock/actions/commit/65b35aa24195ec4341a8e0165601dbaad3092d72)
- Bump jest-circus from 26.6.3 to [27.0.3](https://github.com/Shuttlerock/actions/commit/6feb606dc7aabe307ce42ff8e929db8b7ceaabe8)
- Bump @octokit/webhooks from 9.6.1 to [9.6.3](https://github.com/Shuttlerock/actions/commit/907b77c131533bf441e66faed48ed83e8dc228aa)

Release Candidate 2021-06-02-1222 (Zany Zebra)

---

.meta/SECURITY-436.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/rebase-epic-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
src/services/Github/Branch.ts
src/services/Github/Client.ts
src/services/Github/Git.ts
src/services/Github/Label.ts
src/services/Github/PullRequest.ts
src/services/Github/Release.ts
src/services/Github/Repository.ts
src/services/Github/__tests__/Branch.test.ts
src/services/Github/__tests__/Git.test.ts
src/services/Github/__tests__/Label.test.ts
src/services/Github/__tests__/PullRequest.test.ts
src/services/Github/__tests__/Release.test.ts
src/services/Github/__tests__/Repository.test.ts
src/services/Inputs.ts
src/tests/Mocks.ts

[Jira Task](https://shuttlerock.atlassian.net/browse/SECURITY-436)
For some reason we consistently get a missing Github secret when adding labels:
&#x60;&#x60;&#x60;
Run Shuttlerock&#x2F;actions&#x2F;actions&#x2F;pull-request-labeled-action@master
&#x2F;home&#x2F;runner&#x2F;work&#x2F;_actions&#x2F;Shuttlerock&#x2F;actions&#x2F;master&#x2F;actions&#x2F;pull-request-labeled-action&#x2F;index.js:223
throw new Error(&#x60;Input required and not supplied: ${name}&#x60;);
^
Error: Input required and not supplied: write-token
at getInput (&#x2F;home&#x2F;runner&#x2F;work&#x2F;_actions&#x2F;Shuttlerock&#x2F;actions&#x2F;master&#x2F;actions&#x2F;pull-request-labeled-action&#x2F;index.js:223:15)
at Inputs_githubWriteToken (&#x2F;home&#x2F;runner&#x2F;work&#x2F;_actions&#x2F;Shuttlerock&#x2F;actions …

[SECURITY-436] Fail gracefully when required Github secrets are missing

---

.meta/SECURITY-506.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/trigger-action/__tests__/fixtures/createPullRequestForJiraIssue.json
src/services/Jira/Issue.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Task](https://shuttlerock.atlassian.net/browse/SECURITY-506)
We use the &#x60;repository&#x60; field now, but it is a custom add-on that isn&#39;t available in &#39;classic&#39; projects. We should also check the &#x60;Components&#x60; field if the &#x60;repository&#x60; is not found.
`act --job trigger_action --eventpath src/actions/trigger-action/__tests__/fixtures/createPullRequestForJiraIssue.json`
None

[SECURITY-506] Allow PRs to be automatically created by Jira component

---

package.json
yarn.lock

- Bump axios from 0.21.1 to [0.21.4](https://github.com/Shuttlerock/actions/commit/ff3035f888278caf4dbabb5fd72cdddb132ec845)
- Bump @octokit/webhooks from 9.12.0 to [9.14.1](https://github.com/Shuttlerock/actions/commit/39435859113f4d43dcedec4f1e0442149f811e65)
- Bump eslint-plugin-github from 4.2.0 to [4.3.0](https://github.com/Shuttlerock/actions/commit/1a4081cfaf44d115c9ee3d57229b235a4928d31c)

Release Candidate 2021-09-13-0135 (Junior Jackal)

---

package.json
yarn.lock

- Bump @types/node-fetch from 2.5.12 to [2.6.1](https://github.com/Shuttlerock/actions/commit/5cad5e56f1e048486e8f9645710be4857588811a)
- Bump typescript from 4.5.2 to [4.6.2](https://github.com/Shuttlerock/actions/commit/ca61dc1a3ac1eee5881d2c6d499fd7569fdc7bce)
- Bump @typescript-eslint/parser from 4.32.0 to [5.13.0](https://github.com/Shuttlerock/actions/commit/0148f0bb17e5bdf55a7b47c25f7a819ede143ebb)
- Bump eslint-plugin-jsx-a11y from 6.4.1 to [6.5.1](https://github.com/Shuttlerock/actions/commit/a7391c6c5cf8705843533d83f9c734659bdea35b)
- Bump @types/lodash from 4.14.175 to [4.14.179](https://github.com/Shuttlerock/actions/commit/8255b5391ddc2349fe1a42be77b1e5e1e2fd8a61)
- Bump prettier from 2.5.0 to [2.5.1](https://github.com/Shuttlerock/actions/commit/302b2827b24ba486af06ef03970429 …

Release Candidate 2022-03-03-1354 (Combative Cuckoo)

---

package.json
yarn.lock

- Bump eslint-import-resolver-typescript from 2.4.0 to [2.7.1](https://github.com/Shuttlerock/actions/commit/0847630939dc1ad197cac20e155a021b34b71f03)
- Bump minimist from 1.2.5 to [1.2.6](https://github.com/Shuttlerock/actions/commit/2fb50ff602b65d452d25b4cd5c5be9d2b063a868)
- Bump lint-staged from 11.1.2 to [12.3.7](https://github.com/Shuttlerock/actions/commit/523bf36360e1ddfc2161008f79c7de178eb4d91e)
- Bump @octokit/webhooks from 9.15.0 to [9.23.0](https://github.com/Shuttlerock/actions/commit/abf1d872dd65af3f9c71f03da832171f299c1450)

Release Candidate 2022-04-11-0218 (Satisfied Skink)

---

package.json
yarn.lock

- Bump @typescript-eslint/parser from 5.13.0 to [5.18.0](https://github.com/Shuttlerock/actions/commit/68a7a834f8290b15ab175ef4c7488a91be761ed4)
- Bump eslint-plugin-jest from 24.4.0 to [26.1.4](https://github.com/Shuttlerock/actions/commit/6268c951981b4706882159abd2c20a5432bc3973)
- Bump eslint-plugin-import from 2.24.2 to [2.26.0](https://github.com/Shuttlerock/actions/commit/d1853dfec9f877bce2daa0cfd17b58adbffc1127)

Release Candidate 2022-04-11-0247 (Just Junglefowl)

---

package.json
yarn.lock

- Bump @types/node from 16.10.2 to [17.0.24](https://github.com/Shuttlerock/actions/commit/23b2ec8223bcb832cf6f0f2450f58e714a6b0b95)
- Bump @slack/web-api from 6.5.1 to [6.7.1](https://github.com/Shuttlerock/actions/commit/8cdf2a0a5ebb38cfbe117c80319d33cd2733d772)
- Bump @vercel/ncc from 0.33.3 to [0.33.4](https://github.com/Shuttlerock/actions/commit/6732f9c83ca917072f8a692f1c5b1f961639c7ba)

Release Candidate 2022-04-18-0606 (Probable Peafowl)

---

package.json
yarn.lock

- Bump @types/lodash from 4.14.179 to [4.14.181](https://github.com/Shuttlerock/actions/commit/d2dc30298503c9e6cb08332dac108469d20fe7da)
- Bump @actions/exec from 1.1.0 to [1.1.1](https://github.com/Shuttlerock/actions/commit/0f0c9d3ee7b040738154664a62877ee6545ab6cd)
- Bump typescript from 4.6.2 to [4.6.3](https://github.com/Shuttlerock/actions/commit/bd2732ddef0661b7faa06f07372657484bd535ae)

Release Candidate 2022-04-18-0614 (Written Whale)

---

.circleci/config.yml
package.json
yarn.lock

- Bump @types/dateformat from 3.0.1 to [5.0.0](https://github.com/Shuttlerock/actions/commit/1a26565ba617ef4568ae75dae5da3e6e602315df)
- Bump eslint-plugin-github from 4.3.0 to [4.3.2](https://github.com/Shuttlerock/actions/commit/2bb5884d9ded72eb5dff234a9d3208f825b32f41)
- Bump unique-names-generator from 4.6.0 to [4.7.1](https://github.com/Shuttlerock/actions/commit/50a6693a5f8c6ed593c53a0fad5a0ae6da0cb417)
- Bump jsdom from 16.4.0 to [16.7.0](https://github.com/Shuttlerock/actions/commit/33eb47bd82eee587ded7758cc4fb03815f3c7039)
- Bump @typescript-eslint/parser from 5.18.0 to [5.41.0](https://github.com/Shuttlerock/actions/commit/f101588b5e1b12d0b8b855c1e17f44833a3168e0)
- Bump @actions/core from 1.6.0 to [1.10.0](https://github.com/Shuttlerock/actions/commit/91339e2cb0998a6db06061cd0a2 …

Release Candidate 2023-01-23-1053 (Typical Trout)
