Shuttlerock/actions

.meta/STUDIO-517.md
actions/trigger-action/index.js
src/actions/test-action/__tests__/index.test.ts
src/actions/trigger-action/index.ts
src/services/Github/__tests__/Branch.test.ts
src/services/Jira/Issue.ts
src/services/Template.ts
src/tests/Setup.ts
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Issue](https:&#x2F;&#x2F;shuttlerock.atlassian.net&#x2F;browse&#x2F;STUDIO-517)
Try to make a PR for a Jira issue with a blank `Repository` custom field.
None.

[STUDIO-517] Fix error creating PRs when the Jira repository field is blank

---

.meta/STUDIO-518.md
actions/trigger-action/index.js
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Issue](https://shuttlerock.atlassian.net/browse/STUDIO-518)
Trigger creation of a pull request - you should get a slack message when we start creating it, and one when we finish.
None.

[STUDIO-518] Notify the user that a PR is being created, since it is quite slow

---

.meta/STUDIO-528.md
actions/trigger-action/index.js
src/services/Template.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Issue](https://shuttlerock.atlassian.net/browse/STUDIO-528)
- How to test feature 1
- Do this
- Do that
- Success
- How to test feature 2
- How to test feature 3
It requires new Environmental variables:
- `EXAMPLE_ENV_VARIABLE=content`
- `EXAMPLE_ENV_VARIABLE2=content`

[STUDIO-528] Include the name of the issue type in the Github PR link

---

.meta/STUDIO-533.md
actions/trigger-action/index.js
src/triggers/createPullRequestForJiraIssue.ts

[Jira Task](https://shuttlerock.atlassian.net/browse/STUDIO-533)
Make a new PR via Jira. The git branch should have the first name from the user's email address at the beginning.
None.

[STUDIO-533] Include the user's name in the git branch name

---

.meta/STUDIO-603.md
actions/trigger-action/index.js
src/services/Credentials.ts
src/services/Jira/Issue.ts
src/services/__tests__/Credentials.test.ts
src/tests/Mocks.ts
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-603)
Make your email address private in Jira, and add your Jira user name in https://next.shuttlerock.com/integrations/edit . When a PR is created, it should look up the user by Jira name instead of email, if email is not available.
None.

[STUDIO-603] Handle users with private Jira email addresses

---

.circleci/config.yml
.meta/STUDIO-535.md
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-converted-to-draft-action/__tests__/index.test.ts
src/actions/pull-request-ready-for-review-action/__tests__/index.test.ts
src/services/Constants.ts
src/services/Github/Epic.ts
src/services/Github/PullRequest.ts
src/services/Github/__tests__/Epic.test.ts
src/services/Github/__tests__/PullRequest.test.ts
src/services/Github/index.ts
src/services/Jira/Issue.ts
src/services/Jira/__tests__/Issue.test.ts
src/services/Template.ts
src/tests/Mocks.ts
src/tests/fixtures/github-pull-request-payload.json
src/tests/fixtures/jira-pull-requests.json
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-535)
Triggering the job for issue `236` should create 2 pull requests - the epic PR and the regular PR (which should be based on the epic branch).
```
$ act --job trigger_action --eventpath src/actions/trigger-action/__tests__/fixtures/createPullRequestForJiraIssue.ts.json
```
None.

[STUDIO-535] Moving an epic task to `In Development` should create an Epic PR

---

.github/workflows/pull-request-labeled-action.yml
.meta/STUDIO-581.md
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/action.yml
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/rebase-epic-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-closed-action/pullRequestClosed.ts
src/actions/pull-request-converted-to-draft-action/index.ts
src/actions/pull-request-labeled-action/__tests__/fixtures/pull-request-labeled.json
src/actions/pull-request-labeled-action/__tests__/index.test.ts
src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
src/actions/pull-request-labeled-action/action.yml
src/actions/pull-request-labeled-action/index.ts
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/actions/pull-request-ready-for-review-action/index.ts
src/actions/rebase-epic-action/index.ts
src/services/Constants.ts
src/services/Github/PullRequest.ts
src/services/Github/__tests__/PullRequest.test.ts
src/services/Inputs.ts
src/tests/Mocks.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-581)
`$ act --job pull_request_labeled_action --eventpath src/actions/pull-request-labeled-action/__tests__/fixtures/pull-request-labeled.json`
Set the label on this PR to `in-progress` and run the action. Make sure that the labels finish as `please review` and `under-discussion`.
None.

[STUDIO-581] When a new label is added, remove conflicting labels

---

.circleci/config.yml
.meta/STUDIO-662.md
.meta/STUDIO-665.md

[Jira Story](https://shuttlerock.atlassian.net/browse/STUDIO-665)
[Jira Epic](https://shuttlerock.atlassian.net/browse/STUDIO-662)
Need to update .circleCi.yml, example: [https:&#x2F;&#x2F;github.com&#x2F;Shuttlerock&#x2F;spielberg-api&#x2F;pull&#x2F;2251&#x2F;files|https:&#x2F;&#x2F;github.com&#x2F;Shuttlerock&#x2F;spielberg-api&#x2F;pull&#x2F;2251&#x2F;files]
-check CircleCi
No

[STUDIO-665] Avoid Docker Hub rate limits for your CircleCI builds

---

.meta/STUDIO-662.md

[Jira Epic](https://shuttlerock.atlassian.net/browse/STUDIO-662)
...
...
...
...
Add notes here.

[STUDIO-662] [Epic]  Avoid Docker Hub rate limits for our CircleCI builds

---

.github/workflows/pull-request-ready-for-review-action.yml
.meta/STUDIO-583.md
.secrets.example
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/action.yml
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-ready-for-review-action/__tests__/pullRequestReadyForReview.test.ts
src/actions/pull-request-ready-for-review-action/action.yml
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
src/services/Credentials.ts
src/services/Github/PullRequest.ts
src/services/Github/__tests__/PullRequest.test.ts
src/services/Inputs.ts
src/services/Jira/Issue.ts
src/tests/Mocks.ts
src/tests/Setup.ts
src/tests/fixtures/github-pull-request-payload.json

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-583)
Set a PR as ready-for-review, and check that reviewers get assigned to it.
None

[STUDIO-583] Add reviewers when a PR is set to `Ready for review`

---

.circleci/config.yml

[Jira Chore](https://shuttlerock.atlassian.net/browse/STUDIO-1095)
[Jira Epic](https://shuttlerock.atlassian.net/browse/STUDIO-1091)
See [setup guide|https:&#x2F;&#x2F;circleci.com&#x2F;blog&#x2F;circleci-launches-support-for-jira-software&#x2F;] and [orb docs|https:&#x2F;&#x2F;circleci.com&#x2F;developer&#x2F;orbs&#x2F;orb&#x2F;circleci&#x2F;jira].
Check that the build appears in the `Builds` section in Jira.
None

[STUDIO-1095] Set up CircleCI + Jira integration for actions

---

actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/trigger-action/__tests__/fixtures/jiraStoryPointsUpdated.json
src/actions/trigger-action/index.ts
src/services/Jira/Issue.ts
src/services/Jira/__tests__/Issue.test.ts
src/tests/fixtures/jira-issue.json
src/triggers/__tests__/jiraStoryPointsUpdated.test.ts
src/triggers/index.ts
src/triggers/jiraStoryPointsUpdated.ts

[Jira Story](https://shuttlerock.atlassian.net/browse/STUDIO-1150)
Add an estimate to a issue story, wait 30 seconds for the action to run, and refresh the parent issue - check that the `Story points estimate` field has been updated.
```
$ act --job trigger_action --eventpath src/actions/trigger-action/__tests__/fixtures/jiraStoryPointsUpdated.json
```
None

[STUDIO-1150] Sum story points of child issues in the parent issue

---

actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Jira/Client.ts
src/services/Jira/Issue.ts
src/services/Jira/Project.ts
src/services/Jira/__tests__/Issue.test.ts
src/triggers/__tests__/jiraIssueTransitioned.test.ts
src/triggers/jiraIssueTransitioned.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1200)
Move an issue which is in the backlog to any status except `Ready for planning`. It should be moved to the board (if it wasn't there already).
None

[STUDIO-1200] Move issues to the board if planning has finished

---

.github/workflows/pull-request-closed-action.yml
.github/workflows/pull-request-converted-to-draft-action.yml
.github/workflows/pull-request-labeled-action.yml
.github/workflows/rebase-epic.yml
.meta/STUDIO-1232.md

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1232)
If tests pass, it's ok
None

[STUDIO-1232] Always include the slack-token in workflows, for reporting errors

---

.github/workflows/pull-request-closed-action.yml
.github/workflows/pull-request-converted-to-draft-action.yml
.github/workflows/pull-request-labeled-action.yml
.github/workflows/rebase-epic.yml
.meta/STUDIO-1232.md

- #252 Always include the slack-token in workflows, for reporting errors

Release Candidate 2021-01-04-1151 (Crazy Catshark)

---

.meta/STUDIO-1235.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/action.yml
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/String.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1235)
Hard to test, but if tests pass it should be fine.
None

[STUDIO-1235] Don't use release names that start with X - there's no adjectives

---

.github/workflows/pull-request-closed-action.yml
.github/workflows/pull-request-converted-to-draft-action.yml
.github/workflows/pull-request-labeled-action.yml
.github/workflows/rebase-epic.yml
.meta/STUDIO-1232.md
.meta/STUDIO-1235.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/action.yml
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/services/String.ts
yarn.lock

- #252 Always include the slack-token in workflows, for reporting errors
- #254 Don't use release names that start with X - there's no adjectives
- a7a9503 Bump eslint from 7.16.0 to 7.17.0
- b733ff6 Bump @types/lodash from 4.14.166 to 4.14.167
- fc9317c Bump eslint-plugin-jsdoc from 30.7.9 to 30.7.13
- e3eeb10 Bump js-yaml from 3.14.1 to 4.0.0
- d0720b7 Bump @types/node from 14.14.17 to 14.14.19

Release Candidate 2021-01-05-0246 (Yellow Yak)

---

.meta/STUDIO-1237.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/trigger-action/__tests__/fixtures/createRelease.json
src/services/Constants.ts
src/services/Github/Release.ts
src/services/Github/__tests__/Release.test.ts
src/tests/fixtures/github-pull-request-payload.json

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1237)
Create a release PR, and check that it has both an assigned owner and some labels.
None

[STUDIO-1237] Add an owner and labels when creating a release PR

---

.meta/STUDIO-1219.md
src/triggers/createPullRequestForJiraIssue.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1219)
Make a PR for an issue with a long title.
None

[STUDIO-1219] Limit the length of branch names

---

.meta/STUDIO-1268.md
actions/pull-request-closed-action/action.yml
actions/pull-request-converted-to-draft-action/action.yml
actions/pull-request-labeled-action/action.yml
actions/pull-request-ready-for-review-action/action.yml
actions/rebase-epic-action/action.yml
actions/trigger-action/index.js
src/actions/pull-request-closed-action/action.yml
src/actions/pull-request-converted-to-draft-action/action.yml
src/actions/pull-request-labeled-action/action.yml
src/actions/pull-request-ready-for-review-action/action.yml
src/actions/rebase-epic-action/action.yml

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1268)
If tests pass, it's ok.
None

[STUDIO-1268] Allow slack-token input in all action.yml files

---

.meta/STUDIO-1276.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/rebase-epic-action/index.js
actions/trigger-action/index.js
src/triggers/createPullRequestForJiraIssue.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1276)
Create a PR from a Jira issua with a very long name - the Github action should not break[like this](https://github.com/Shuttlerock/spielberg-ui/runs/1678541299?check_suite_focus=true)
None

[STUDIO-1276] Fix invalid name issue truncating long branch names

---

.meta/STUDIO-1267.md
.meta/STUDIO-1283.md
actions/pull-request-ready-for-review-action/index.js
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts

- #274 Fix ready-for-review action for release PRs
- #276 Fix adding labels to release PRs when they are made ready for review

Release Candidate 2021-01-12-0426 (Explicit Eagle)

---

.github/workflows/pull-request-labeled-action.yml
.meta/STUDIO-690.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/services/Constants.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-690)
Push to `master` and check that adding the `dependencies` label also adds the `please-review` label, and adds reviewers.
None

[STUDIO-690] Add the 'please-review' label to dependabot pull requests, and assign reviewers

---

.github/workflows/pull-request-labeled-action.yml
.meta/STUDIO-690.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/services/Constants.ts

- #283 Add the 'please-review' label to dependabot pull requests, and assign reviewers

Release Candidate 2021-01-13-0405 (Free Flea)

---

.meta/STUDIO-1291.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/services/Github/Release.ts
yarn.lock

- #286 Don't include the Git hash in dependabot summary in release PRs
- 2cf3aba Bump @slack/web-api from 5.15.0 to 6.0.0

Release Candidate 2021-01-13-0857 (Hidden Hoverfly)

---

.github/workflows/pull-request-closed-action.yml
.meta/STUDIO-1231.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/action.yml
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/action.yml
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
src/actions/pull-request-closed-action/action.yml
src/actions/pull-request-closed-action/pullRequestClosed.ts
src/services/Credentials.ts
src/services/Github/PullRequest.ts
src/services/Github/__tests__/PullRequest.test.ts
src/services/Jira/Issue.ts
src/services/Jira/Project.ts
src/services/Jira/Release.ts
src/services/Jira/__tests__/Issue.test.ts
src/services/Jira/__tests__/Project.test.ts
src/services/Jira/__tests__/Release.test.ts
src/services/Jira/index.ts
src/tests/Mocks.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1231)
Push to master, and merge a release PR - it should also create a release in Jira.
None

[STUDIO-1231] Create a Jira release when a release PR is merged

---

.meta/STUDIO-1327.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Jira/Release.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1327)
Merge a release with no Jira issues in the commit comments (eg. only dependabot updates), and make sure it creates a release in Jira.
None

[STUDIO-1327] Fix creation of releases when no Jira issues are included

---

.meta/STUDIO-1327.md
actions/check-run-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Jira/Release.ts

- #304 Fix creation of releases when no Jira issues are included

Release Candidate 2021-01-20-0802 (Leading Llama)

---

.meta/STUDIO-1344.md

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1344)
- How to test feature 1
- Do this
- Do that
- Success
- How to test feature 2
- How to test feature 3
It requires new Environmental variables:
- `EXAMPLE_ENV_VARIABLE=content`
- `EXAMPLE_ENV_VARIABLE2=content`

[STUDIO-1344] Release demonstration bug

---

.meta/STUDIO-1344.md

- #306 Release demonstration bug

Release Candidate 2021-01-22-0109 (Beneficial Bovid)

---

.meta/STUDIO-1346.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
src/actions/check-suite-completed-action/checkSuiteCompleted.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1346)
Not sure.
None

[STUDIO-1346] Handle null commits when analyzing check runs

---

.meta/STUDIO-1346.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
src/actions/check-suite-completed-action/checkSuiteCompleted.ts

- #312 Handle null commits when analyzing check runs

Release Candidate 2021-01-22-1211 (Ordinary Owl)

---

.meta/STUDIO-1347.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
src/actions/check-suite-completed-action/checkSuiteCompleted.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1347)
Not sure what situation causes this to be null...
None

[STUDIO-1347] Handle null pull request lists when analyzing check runs

---

.meta/STUDIO-1348.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
src/actions/check-suite-completed-action/checkSuiteCompleted.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1348)
Not sure
None

[STUDIO-1348] Handle null commits when analyzing check runs, take 2

---

.meta/STUDIO-1347.md
.meta/STUDIO-1348.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
src/actions/check-suite-completed-action/checkSuiteCompleted.ts

- #316 Handle null pull request lists when analyzing check runs
- #318 Handle null commits when analyzing check runs, take 2

Release Candidate 2021-01-22-0136 (Kind Krill)

---

.meta/STUDIO-1260.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Slack/Message.ts
src/services/Slack/__tests__/Message.test.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1260)
!Screen Shot 2021-01-08 at 9.43.57.png|width&#x3D;1219,height&#x3D;124!
If tests pass, it works.
None

[STUDIO-1260] Scrub sensitive data before logging errors

---

.meta/STUDIO-1384.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/trigger-action/__tests__/fixtures/createRelease.json
src/services/Github/Release.ts

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1384)
Create a release - you should see a link to the Jira issue for each pull request (if one exists).
None

[STUDIO-1384] Add a Jira link to the release notes

---

.meta/STUDIO-1314.md

[Jira Tech task](https://shuttlerock.atlassian.net/browse/STUDIO-1314)
If the tests pass, it works.
None

[STUDIO-1314] If at least ONE of tech stories is in ['In Development', 'Tech Review', 'Has Issues'], then the parent story should be 'In Development'

---

.meta/STUDIO-1260.md
.meta/STUDIO-1314.md
.meta/STUDIO-1384.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/actions/trigger-action/__tests__/fixtures/createRelease.json
src/services/Github/Release.ts
src/services/Slack/Message.ts
src/services/Slack/__tests__/Message.test.ts
src/triggers/jiraIssueTransitioned.ts
yarn.lock

- #329 Scrub sensitive data before logging errors
- #328 Add a Jira link to the release notes
- #330 If at least ONE of tech stories is in , then the parent story should be 'In Development'
- #331 If at least ONE of tech stories is in , then the parent story should be 'In Development'
- Bump eslint-plugin-jsdoc from 31.3.2 to [31.3.3](https://github.com/Shuttlerock/actions/commit/cb2e0583d312689bb729dc878adc994592ea360f)
- Bump @typescript-eslint/parser from 4.14.0 to [4.14.1](https://github.com/Shuttlerock/actions/commit/19bce457dc7fa7801c069d3ea5e31b919c84867f)
- Bump eslint-plugin-jsdoc from 31.3.3 to [31.4.0](https://github.com/Shuttlerock/actions/commit/e82700deb23493e1e4e6136240144d512d7c0c2b)

Release Candidate 2021-02-01-0107 (Lovely Loon)

---

.meta/STUDIO-1385.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Slack/Message.ts
src/services/Slack/__tests__/Message.test.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1385)
If tests pass, it works.
None

[STUDIO-1385] Don't scrub secrets from user messages

---

.meta/STUDIO-1385.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Slack/Message.ts
src/services/Slack/__tests__/Message.test.ts

- #333 Don't scrub secrets from user messages ([STUDIO-1385](https://shuttlerock.atlassian.net/browse/STUDIO-1385))

Release Candidate 2021-02-01-0438 (Total Tiger)

---

.meta/STUDIO-1463.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/trigger-action/__tests__/fixtures/approvePullRequest.json
src/actions/trigger-action/index.ts
src/services/Credentials.ts
src/services/Github/PullRequest.ts
src/services/Github/__tests__/PullRequest.test.ts
src/services/Slack/Message.ts
src/tests/Mocks.ts
src/triggers/__tests__/approvePullRequest.test.ts
src/triggers/approvePullRequest.ts
src/triggers/index.ts

[Jira Story](https://shuttlerock.atlassian.net/browse/STUDIO-1463)
`act --job trigger_action --eventpath src/actions/trigger-action/__tests__/fixtures/approvePullRequest.json`
The @sr-devops user should approve the PR defined in the JSON.
None

[STUDIO-1463] Allow selected repositories to be auto-approved via Slack

---

.meta/STUDIO-1469.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Github/Release.ts

[Jira Story](https://shuttlerock.atlassian.net/browse/STUDIO-1469)
If tests pass, it works.
None

[STUDIO-1469] Linkify the Slack response message after creating a release PR

---

.meta/STUDIO-1469.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Github/Release.ts

- #349 Linkify the Slack response message after creating a release PR ([STUDIO-1469](https://shuttlerock.atlassian.net/browse/STUDIO-1469))

Release Candidate 2021-02-08-0110 (Young Yak)

---

.meta/STUDIO-1470.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/check-suite-completed-action/__tests__/checkSuiteCompleted.test.ts
src/actions/check-suite-completed-action/checkSuiteCompleted.ts
src/services/Github/Release.ts
src/triggers/__tests__/approvePullRequest.test.ts
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/approvePullRequest.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Story](https://shuttlerock.atlassian.net/browse/STUDIO-1470)
If tests pass, it should be ok.
None

[STUDIO-1470] Make link style consistent in Slack messages

---

.meta/STUDIO-1471.md
actions/pull-request-closed-action/index.js
src/actions/pull-request-closed-action/pullRequestClosed.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1471)
If tests pass, it should be fine.
None

[STUDIO-1471] Fix bug that moves Jira issues twice after a release

---

.meta/STUDIO-1470.md
.meta/STUDIO-1471.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/check-suite-completed-action/__tests__/checkSuiteCompleted.test.ts
src/actions/check-suite-completed-action/checkSuiteCompleted.ts
src/actions/pull-request-closed-action/pullRequestClosed.ts
src/services/Github/Release.ts
src/triggers/__tests__/approvePullRequest.test.ts
src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
src/triggers/approvePullRequest.ts
src/triggers/createPullRequestForJiraIssue.ts

- #351 Make link style consistent in Slack messages ([STUDIO-1470](https://shuttlerock.atlassian.net/browse/STUDIO-1470))
- #353 Fix bug that moves Jira issues twice after a release ([STUDIO-1471](https://shuttlerock.atlassian.net/browse/STUDIO-1471))

Release Candidate 2021-02-08-0556 (Chemical Cheetah)

---

.meta/STUDIO-1566.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Github/Release.ts
src/services/Github/__tests__/Release.test.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1566)
Create a release for `spielberg-ui` - it is breaking currently.
None

[STUDIO-1566] Don't assume that a commit author will have a Github login

---

.meta/STUDIO-1567.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Github/Release.ts
src/services/Github/__tests__/Release.test.ts

[Jira Bug](https://shuttlerock.atlassian.net/browse/STUDIO-1567)
Create a release for `spielberg-ui` - it is breaking currently.
None

[STUDIO-1567] Don't assume that a commit author will have a Github login, take 2

---

.circleci/config.yml
.meta/STUDIO-1568.md

[Jira Story](https://shuttlerock.atlassian.net/browse/STUDIO-1568)
We&#39;re getting lots of random out-of-memory and file-not-found errors
If tests pass, it works.
None

[STUDIO-1568] Use a bigger CircleCI instance for selected tests

---

.meta/SECURITY-177.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/actions/pull-request-ready-for-review-action/__tests__/pullRequestReadyForReview.test.ts
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
src/services/Constants.ts

- #434 Auto-assign dependabot and security PRs to the project tech lead ([SECURITY-177](https://shuttlerock.atlassian.net/browse/SECURITY-177))

Release Candidate 2021-03-24-0546 (Rigid Rat)

---

.meta/SHARED-75.md
actions/pull-request-labeled-action/index.js
package.json
src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
yarn.lock

- #446 Fix mutually-exclusive label assignment ([SHARED-75](https://shuttlerock.atlassian.net/browse/SHARED-75))
- Bump @octokit/webhooks from 8.5.4 to [8.8.0](https://github.com/Shuttlerock/actions/commit/920e38b8a37c0687dcb7d0b716d607bc7c39f296)
- Bump @types/jest from 26.0.20 to [26.0.22](https://github.com/Shuttlerock/actions/commit/f30081ef17276a6189426bac789abb633b588243)
- Bump eslint-plugin-jest from 24.3.1 to [24.3.2](https://github.com/Shuttlerock/actions/commit/141dea4805e9fd5acd714cc5abc01c5c359a6482)

Release Candidate 2021-03-30-1210 (Vast Viper)

---

.meta/SHARED-77.md
README.md

[Jira Chore](https://shuttlerock.atlassian.net/browse/SHARED-77)
N/A - only documentation updates.
None

[SHARED-77] Document the Github actions automation

---

.meta/SHARED-77.md
README.md
package.json
yarn.lock

- #463 Document the Github actions automation ([SHARED-77](https://shuttlerock.atlassian.net/browse/SHARED-77))
- Bump eslint-plugin-unused-imports from 1.1.0 to [1.1.1](https://github.com/Shuttlerock/actions/commit/a85fe33b863fedca5c13245932311db5150da820)
- Bump @octokit/webhooks-definitions from 3.65.6 to [3.66.0](https://github.com/Shuttlerock/actions/commit/42c58c5f7e9495bf01896828fb871978e907911e)
- Bump @octokit/webhooks from 8.10.1 to [8.11.2](https://github.com/Shuttlerock/actions/commit/33486a4cee008fd97cbc1e1cc858280b2caad7c9)

Release Candidate 2021-04-05-0642 (Tender Tahr)

---

.meta/STUDIO-1859.md
README.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
src/services/Github/Release.ts

- #469 Handle errors during release creation more gracefully ([STUDIO-1859](https://shuttlerock.atlassian.net/browse/STUDIO-1859))

Release Candidate 2021-04-12-0346 (Inappropriate Iguana)

---

.gitignore
.meta/STUDIO-2037.md
actions/pull-request-closed-action/index.js
actions/trigger-action/index.js
src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
src/actions/pull-request-closed-action/pullRequestClosed.ts
src/services/Credentials.ts
src/tests/Mocks.ts
src/triggers/createPullRequestForJiraIssue.ts

[Jira Story](https://shuttlerock.atlassian.net/browse/STUDIO-2037)
Releases should no longer be published to Jira automatically when they are released.
- Tests should be green
None

[STUDIO-2037] Remove Jira Release Publish Automation from (Slackbot | Git Actions)

---

.github/PULL_REQUEST_TEMPLATE.md

Update repository configuration to the latest defaults.

[devops] Update repository configuration

---

.github/PULL_REQUEST_TEMPLATE.md
package.json
yarn.lock

- #542 Update repository configuration
- Bump eslint-plugin-jsdoc from 34.8.1 to [34.8.2](https://github.com/Shuttlerock/actions/commit/9d44d99efb6c48c19a36a0cfe896a23045d99d59)
- Bump @types/node from 15.3.0 to [15.3.1](https://github.com/Shuttlerock/actions/commit/233231a5b70c9b753b11507c2507447c8a6b342f)
- Bump ws from 7.3.1 to [7.4.6](https://github.com/Shuttlerock/actions/commit/1b1611273aba256eefe8aeaa3a7065c5bac5c1c3)
- Bump @types/node from 15.3.1 to [15.6.1](https://github.com/Shuttlerock/actions/commit/47e3963d08ab6cab3ad052d867dc4361720d3eec)
- Bump @actions/core from 1.2.7 to [1.3.0](https://github.com/Shuttlerock/actions/commit/99501205717ad45e92ce2491700a29452068b6bb)
- Bump @types/lodash from 4.14.169 to [4.14.170](https://github.com/Shuttlerock/actions/commit/48f3c09816ca37 …

Release Candidate 2021-06-02-1223 (Strict Salmon)

---

package.json
yarn.lock

- Bump @actions/core from 1.3.0 to [1.4.0](https://github.com/Shuttlerock/actions/commit/bcd37b0234840de0ff26fa2647a6d480fb60a112)

Release Candidate 2021-06-17-0500 (Biological Bug)

---

actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
src/services/Inputs.ts
yarn.lock

- #567 Fail gracefully when required Github secrets are missing ([SECURITY-436](https://shuttlerock.atlassian.net/browse/SECURITY-436))
- Bump @octokit/webhooks from 9.6.3 to [9.8.0](https://github.com/Shuttlerock/actions/commit/db109409dfb811aad12b513e46883b3ce14d886b)
- Bump @typescript-eslint/parser from 4.26.0 to [4.28.1](https://github.com/Shuttlerock/actions/commit/fa98d6ec25082d8e56bcdda96815a4f12d322ef9)
- Bump @slack/web-api from 6.2.3 to [6.2.4](https://github.com/Shuttlerock/actions/commit/775900a45540d5990d4530362c3de32bacb35dee)
- Bump eslint-plugin-jsdoc from 35.1.3 to [35.4.1](https://github.com/Shuttlerock/actions/commit/05e5f744253df4baa52d65a816fa74635e35eab8)
- Bump prettier from 2.3.0 to [2.3.2](https://github.com/Shuttlerock/actions/commit/125c9fd1b7ec130f86d265ea69c0b …

Release Candidate 2021-07-07-1058 (Great Gamefowl)

---

.meta/SECURITY-436.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/rebase-epic-action/index.js
actions/trigger-action/index.js
package.json
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
src/services/Github/Branch.ts
src/services/Github/Client.ts
src/services/Github/Git.ts
src/services/Github/Label.ts
src/services/Github/PullRequest.ts
src/services/Github/Release.ts
src/services/Github/Repository.ts
src/services/Github/__tests__/Branch.test.ts
src/services/Github/__tests__/Git.test.ts
src/services/Github/__tests__/Label.test.ts
src/services/Github/__tests__/PullRequest.test.ts
src/services/Github/__tests__/Release.test.ts
src/services/Github/__tests__/Repository.test.ts
src/services/Inputs.ts
src/tests/Mocks.ts
yarn.lock

- #567 Fail gracefully when required Github secrets are missing ([SECURITY-436](https://shuttlerock.atlassian.net/browse/SECURITY-436))
- Bump @octokit/webhooks from 9.6.3 to [9.8.0](https://github.com/Shuttlerock/actions/commit/db109409dfb811aad12b513e46883b3ce14d886b)
- Bump @typescript-eslint/parser from 4.26.0 to [4.28.1](https://github.com/Shuttlerock/actions/commit/fa98d6ec25082d8e56bcdda96815a4f12d322ef9)
- Bump @slack/web-api from 6.2.3 to [6.2.4](https://github.com/Shuttlerock/actions/commit/775900a45540d5990d4530362c3de32bacb35dee)
- Bump eslint-plugin-jsdoc from 35.1.3 to [35.4.1](https://github.com/Shuttlerock/actions/commit/05e5f744253df4baa52d65a816fa74635e35eab8)
- Bump prettier from 2.3.0 to [2.3.2](https://github.com/Shuttlerock/actions/commit/125c9fd1b7ec130f86d265ea69c0b …

Release Candidate 2021-07-28-0146 (Zany Zebra)

---

actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js

Release Candidate 2021-07-28-0211 (Innovative Iguana)

---

.meta/SECURITY-506.md
actions/check-run-completed-action/index.js
actions/check-suite-completed-action/index.js
actions/pull-request-closed-action/index.js
actions/pull-request-converted-to-draft-action/index.js
actions/pull-request-labeled-action/index.js
actions/pull-request-ready-for-review-action/index.js
actions/trigger-action/index.js
package.json
src/actions/check-suite-completed-action/checkSuiteCompleted.ts
src/actions/pull-request-labeled-action/pullRequestLabeled.ts
src/actions/trigger-action/__tests__/fixtures/createPullRequestForJiraIssue.json
src/services/Github/Branch.ts
src/services/Github/PullRequest.ts
src/services/Jira/Issue.ts
src/services/Slack/Message.ts
src/triggers/createPullRequestForJiraIssue.ts
yarn.lock

- #637 Allow PRs to be automatically created by Jira component ([SECURITY-506](https://shuttlerock.atlassian.net/browse/SECURITY-506))
- Bump @slack/web-api from 6.3.0 to [6.4.0](https://github.com/Shuttlerock/actions/commit/4acdaefe3a11dcd5670b89d3626c8fec577907b0)
- Bump eslint-plugin-prettier from 3.4.0 to [3.4.1](https://github.com/Shuttlerock/actions/commit/c9e3bc37a979e8bebd563ca71af529bf625ebabd)
- Bump @vercel/ncc from 0.29.2 to [0.30.0](https://github.com/Shuttlerock/actions/commit/0dc812cd357ee6e63dec6171a64d1d4bb01fec2f)
- Bump @octokit/webhooks-types from 4.3.0 to [4.3.1](https://github.com/Shuttlerock/actions/commit/3e8f112da09fd52ef260e2d40ffabfcab3d76bae)
- Bump typescript from 4.3.5 to [4.4.2](https://github.com/Shuttlerock/actions/commit/5e4e40f1501b4b754f2336f972c3a2ab934 …

Release Candidate 2021-08-30-0753 (Striped Scorpion)

---

.circleci/config.yml

[Story Link](https://shuttlerock.atlassian.net/browse/ORANGE-1219)
Email:
> Your organization is receiving this email because there are still legacy convenience images being used. These images are being deprecated in two rounds - the first round was on December 31, 2021. They will not be deleted, but they will no longer be supported. You should have received emails about the specific images in September/October of last year.
> 
> Some images and tags have undergone significant changes and there may be some configuration changes that need to be made beyond the image name. For a list of affected images and tags, please take a look at [our Discuss post about the deprecation](http://gslink.circleci.com/ls/click?upn=2xX95wS72SYPIyQ6OjEQpX6b5-2Fd-2Bif2FUWbzNf8tGbomdM39u-2F3wa1zvPqY5B8JIXH7nMEuOG …

[ORANGE-1219] Check/update circleCI images

---

.github/workflows/test.yml

Add a Github action for tests

---

.github/workflows/test.yml
package.json
yarn.lock

- Bump word-wrap from 1.2.3 to [1.2.4](https://github.com/Shuttlerock/actions/commit/214e5d8820b5b1a2563b4890cc50e30a59a0c9a9)
- Bump semver from 5.7.1 to [5.7.2](https://github.com/Shuttlerock/actions/commit/d95fc74bb04f23f35e20772be4e194011c1e9b07)
- Bump eslint-plugin-import from 2.26.0 to [2.27.5](https://github.com/Shuttlerock/actions/commit/d1f2d34b8e9e041a8c7b47922eef526cc09f0c87)
- Bump jira-client from 8.0.0 to [8.2.2](https://github.com/Shuttlerock/actions/commit/cc7518554c5ad10bbd58c8eef64b328a2d978757)
- Bump lint-staged from 12.3.7 to [14.0.1](https://github.com/Shuttlerock/actions/commit/f847a5ce77e61493e21ce7e86bdfd9c1f25c117a)

Release Candidate 2023-09-11-0453 (Automatic Armadillo)
